spring.application.name=wave

# Configurações do H2 (Modo Arquivo Físico)
spring.h2.console.enabled=true
# Cria um arquivo chamado 'wavedb' na raiz do seu projeto backend
spring.datasource.url=jdbc:h2:file:./wavedb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.defer-datasource-initialization=true

# Hibernate (Para criar e atualizar as tabelas no H2)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Segurança JWT (O TokenService precisa disso para não dar erro)
api.security.token.secret=chave-secreta-local-wave-123456

# Credenciais Iniciais (O DataInitializerConfig precisa disso)
app.admin1.email=admin@wave.com
app.admin1.password=123456
app.admin2.email=admin2@wave.com
app.admin2.password=123456